name: share_plus_example
description: Demonstrates how to use the share_plus plugin.
publish_to: none

dependencies:
  flutter:
    sdk: flutter
  share_plus:
    path: ../
 

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/flutter_logo.png

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: '>=3.19.6'
