name: share_plus
description: Flutter plugin for sharing content via the platform share UI, using the ACTION_SEND intent on Android and UIActivityViewController on iOS.
version: 13.1.0
homepage: https://github.com/fluttercommunity/plus_plugins
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/share_plus/share_plus
issue_tracker: https://github.com/fluttercommunity/plus_plugins/labels/share_plus
publish_to: none
topics:
  - share
  - utils

flutter:
  plugin:
    platforms:
      android:
        package: dev.fluttercommunity.plus.share
        pluginClass: SharePlusPlugin
      ios:
        pluginClass: FPPSharePlusPlugin
      linux:
        dartPluginClass: SharePlusLinuxPlugin
      macos:
        pluginClass: SharePlusMacosPlugin
      web:
        pluginClass: SharePlusWebPlugin
        fileName: src/share_plus_web.dart
      windows:
        dartPluginClass: SharePlusWindowsPlugin
        pluginClass: SharePlusWindowsPluginCApi

dependencies:
  cross_file: ^0.3.5+2
  meta: ^1.17.0
  mime: ^2.0.0
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  share_plus_platform_interface:
    git: "https://github.com/kumsumit/share_plus_platform_interface.git"
  file: ^7.0.1
  url_launcher_web:
    git: "https://github.com/kumsumit/url_launcher_web.git"
  url_launcher_windows:
    git: "https://github.com/kumsumit/url_launcher_windows.git"
  url_launcher_linux:
    git: "https://github.com/kumsumit/url_launcher_linux.git"
  url_launcher_platform_interface: 
    git: "https://github.com/kumsumit/url_launcher_platform_interface.git"
  ffi: ^2.2.0
  web: ^1.1.1
  win32: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

environment:
  sdk: ">=3.11.0 <4.0.0"
  flutter: ">=3.41.1"

